# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        /:title

# Setup
title:            Danielle Hill
tagline:          'A personal portfolio'
description:      Web Developer
url:              "http://danie11e.com"
baseurl:          /

author:
  #name:           'Danielle Hill'
  #url:            https://twitter.com/mdo

paginate:         3

#Custom vars
version:          3.1.2

gems: [jekyll-paginate, jekyll-gist]
